name: Build-Inputer

on:
  push:
    paths:
    - '**.py'
    - '**.yml'
  pull_request:
    paths:
    - '**.py'
    - '**.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Download Sources For Windows
      if: matrix.os == 'windows-latest'
      run: |
        curl -O 'Gfriends Inputer.py' 'https://raw.githubusercontent.com/xinxin8816/gfriends/master/Gfriends Inputer.py'
        curl --help

    - name: Download Sources For Mac/Linux
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      run: |
        wget 'https://raw.githubusercontent.com/xinxin8816/gfriends/master/Gfriends Inputer.py'

    - name: Install Dependencies and Build
      run: |
        python -m pip install --upgrade pip
        pip install alive-progress
        pip install requests
        pip install Pillow
        pip install pyinstaller
        pyinstaller -F 'Gfriends Inputer.py'

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Gfriends-Inputer-${{ matrix.os }}
        path: dist
